<?php 
    $lang = array (
        "profile" => "Perfil",
        "thisIsProfile" => ", este es tu perfil",
        "updateInfo" => "Actualizar informacion:",
        "newEmail" => "Nuevo email",
        "newPass" => "Nueva contraseña",
        "confirmPass" => "Confirmar contraseña",
        "currentPass" => "Contraseña actual",
        "updateInfo" => "Actualizar información",
        "sessionAndAccount" => "Sesion y cuenta:",
        "closeSession" => "Cerrar sesion",
        "deleteAccount" => "Borra cuenta",
        "deleteAccountSure" => "¿Estas seguro de querere borrar tu cuenta?",
        "notReversed" => "Esta accion no tiene vuelta atras",
        "cancel" => "Cancelar",
        "return" => "Volver",
        "options" => "Opciones de interfaz:",
        "language" => "Idioma:",
        "spanish" => "Español",
        "english" => "Ingles",
        "theme" => "Tema:",
        "light" => "Claro",
        "dark" => "Oscuro",
        "save" => "Guardar opciones",
        "contactTheDevelopers" => "Contacta a los desarrolladores:",
        "message" => "Mensaje",
        "subject" => "Asunto",
        "send" => "Enviar",
        "resetAccount" => "Reiniciar cuenta",
        "resetAccountSure" => "Si reinicias tu cuenta se borrarán tus habitos, tareas, recompensas y puntos.",
        "uploadImage" => "Cambiar imagen de avatar:",
        "saveImage" => "Guardar imagen",
        "searchImage" => "Buscar imagen"

    );
?>