<?php
    $lang = array (
        "welcome" => "Welcome",
        "profile" => "Profile",
        "points" => "Points: ",
        "habits" => "Habits",
        "newHabit" => "New habit",
        "tasks" => "Tasks",
        "newTask" => "New task",
        "dailyTasks" => "Daily tasks",
        "newDailyTask" => "New daily task",
        "rewards" => "Rewards",
        "newReward" => "New Reward",
        "name" => "Name: ",
        "type" => "Type: ",
        "positive" => "Positive",
        "negative" => "Negative",
        "neutral" => "Neutral",
        "rewardPoints" => "Reward points: ",
        "cancel" => "Cancel",
        "description" => "Description: ",
        "price" => "Price:",
        "accept" => "Accept",
        "editHabit" => "Edit habit",
        "edit" => "Edit",
        "editTask" => "Edit task",
        "editDailyTask" => "Edit daily task",
        "editReward" => "Edit reward"
    );
?>